codeofconductlink/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
import projects.views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^profiles/', include('profiles.urls', namespace='profiles')),
    url(r'^projects/', include('projects.urls', namespace='projects')),
    url(r'^reports/', include('reports.urls', namespace='reports')),
    url(r'^$', projects.views.ProjectIndex.as_view(), name='index'),
]

projects/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.ProjectIndex.as_view(), name='index'),
    url(r'^new/$', views.CreateProject.as_view(), name='create'),

    url(r'^(?P<pk>[0-9]+)/$',                   views.ProjectDetail.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)-(?P<name>[-_\w]+)/$', views.ProjectDetail.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/update$', views.ProjectUpdate.as_view(), name='update'),
    url(r'^(?P<pk>[0-9]+)/delete$', views.ProjectDelete.as_view(), name='delete'),
    url(r'^(?P<pk>[0-9]+)/verify$', views.ProjectVerify.as_view(), name='verify'),

    url(r'^tag/(?P<tag>[-_\w]+)/$', views.ProjectIndexByTag.as_view(), name='list-by-tag'),

    url(r'^vouch/$', views.ToggleVouch.as_view(), name='vouch'),

    url(r'^(?P<pk>[0-9]+)/submissions/create$', views.SubmissionCreate.as_view(), name='create-submission'),
    url(r'^(?P<pk>[0-9]+)-(?P<name>[-_\w]+)/submission/create$', views.SubmissionCreate.as_view(), name='create-submission'),
    url(r'^submissions/(?P<pk>[0-9]+)/verify$', views.SubmissionVerify.as_view(), name='verify-submission'),
]

reports/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^new/', views.CreateReport.as_view(), name='new'),
    url(r'^(?P<pk>[0-9]+)/update$', views.UpdateReport.as_view(), name='update'),
    url(r'^(?P<pk>[0-9]+)/delete$', views.DeleteReport.as_view(), name='delete'),
]

projects/models.py
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models import Q
from django.conf import settings
from django.utils import timezone
from django.utils.text import slugify
from taggit.managers import TaggableManager
from reports.models import Report

class Vouch(models.Model):
    content_type   = models.ForeignKey(ContentType)
    object_id      = models.PositiveIntegerField()
    content_object = GenericForeignKey()

    user           = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='vouches')
    created_date   = models.DateTimeField(default=timezone.now)

    @staticmethod
    def get_url(target):
        return '{path}?model={model}&pk={pk}'.format(path=reverse('projects:vouch'),
                                                     model=target.__class__.__name__,
                                                     pk=target.pk)

    @staticmethod
    def toggle_vouch(target, user):
        v = target.vouches.filter(user=user)
        if v.exists():
            v.delete()
            return target.undo_vouch_message()
        Vouch.objects.create(content_object=target, user=user)
        return target.vouch_message()

    @staticmethod
    def has_vouched(target, user):
        return target.vouches.filter(user=user).exists()


class VerifiedModel(models.Model):
    class Meta:
        abstract = True

    verified_date = models.DateTimeField(blank=True, null=True)
    verified_by   = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True,
                                      related_name='%(class)s_verifications')

    def verify(self, verifying_user, save=True):
        self.verified_date = timezone.now()
        self.verified_by   = verifying_user
        if save:
            self.save()

class Project(VerifiedModel):
    user            = models.ForeignKey(settings.AUTH_USER_MODEL)
    created_date    = models.DateTimeField(default=timezone.now)
    name            = models.CharField(max_length=256, unique=True)
    homepage        = models.URLField(blank=True, null=True)
    code_of_conduct = models.URLField(blank=True, null=True)
    tags            = TaggableManager(blank=True)
    reports         = GenericRelation(Report)
    vouches         = GenericRelation(Vouch)

    def vouch_message(self):
        return 'You have vouched for the {} project community.'.format(self.name)

    def undo_vouch_message(self):
        return 'You no longer vouch for the {} project community.'.format(self.name)

    def get_vouch_url(self):
        return Vouch.get_url(self)

    def get_report_url(self):
        return '{}?model=Project&pk={}&target={}'.format(reverse('reports:new'), self.pk, self.name)

    def get_absolute_url(self):
        return reverse('projects:detail', args=(self.pk, slugify(self.name),))

    def get_submissions_for_user(self, request_user):
        if request_user.is_authenticated() and request_user.is_moderator:
            return self.submissions.all()

        return self.submissions.filter(
            Q(verified_date__isnull=False) |
            Q(user=request_user)
        )

    def get_reports_for_user(self, request_user):
        # All reports should be visible to moderators. Reports that have
        # opted in to being visible to the owner should be visible to the owner
        # if they're logged in. Otherwise, only your own reports are visible.
        if request_user.is_authenticated():
            if request_user.is_moderator:
                return self.reports

            # Project owner
            owner = Q(visible_to_owner=True)
            by_user = Q(user=request_user)
            if self.user == request_user:
                return self.reports.filter(owner | by_user)
            return self.reports.filter(by_user)

    def __str__(self):
        return self.name

class Submission(VerifiedModel):
    # A submission is a piece of information about a project. Examples:
    # tags=('queer','contributor') is_contributor=True, url='http://emilyhorsman.com',
    #   public_message='Emily Horsman is a core contributor and identifies as queer.',
    #   private_message='You can contact her @emilymhorsman to verify.'
    # tags=('problematic conduct') url=https://github.com/opal/opal/issues/941#issuecomment-113219234,
    #   public_message='Ignoring transphobia.'
    user            = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='submissions')
    project         = models.ForeignKey(Project, related_name='submissions')
    tags            = TaggableManager(help_text='Tag a submission to describe its content. Is it "problematic content"? A link to a "queer" contributor?')
    is_contributor  = models.BooleanField(default=False, help_text='Is this submission describing a project author/contributor?')
    url             = models.URLField()
    public_message  = models.TextField(blank=True, null=True, help_text='This message will publicly accompany the submission.')
    private_message = models.TextField(blank=True, null=True, help_text='This message will only be displayed to moderators verifying the submission.')
    created_date    = models.DateTimeField(default=timezone.now)
    updated_date    = models.DateTimeField(default=timezone.now)
    reports         = GenericRelation(Report)
    vouches         = GenericRelation(Vouch)

    def __str__(self):
        return self.url

projects/forms.py
from django.forms import models
from crispy_forms.layout import Submit, Layout, Fieldset, Field
from common.forms import pure_helper, create_crispy_model_form
from profiles.recaptcha import ReCAPTCHAField
from .models import Project, Report, Submission

class CreateProjectForm(models.ModelForm):
    class Meta:
        model = Project
        fields = ('name', 'homepage', 'code_of_conduct', 'tags',)

    recaptcha = ReCAPTCHAField(label='')

    def __init__(self, *args, **kwargs):
        super(CreateProjectForm, self).__init__(*args, **kwargs)
        self.helper = pure_helper()
        self.helper.layout = Layout(
            Fieldset('Submit a new project for tracking', 'recaptcha', *self.Meta.fields),
            Submit('submit', 'Create', css_class='pure-button pure-button-primary')
        )


class UpdateProjectForm(create_crispy_model_form(
                        legend_text='Edit Project')):
    class Meta:
        model = Project
        fields = ('name', 'homepage', 'code_of_conduct', 'tags',)

class CreateSubmissionForm(models.ModelForm):
    class Meta:
        model = Submission
        fields = ('url', 'tags', 'is_contributor', 'public_message', 'private_message',)
        labels = {
            'url': 'URL',
        }

    def __init__(self, *args, **kwargs):
        project = kwargs.pop('project')
        super(CreateSubmissionForm, self).__init__(*args, **kwargs)

        self.fields['url'].widget.attrs['placeholder'] = 'https://somecontributorhomepage.alice'
        self.fields['tags'].widget.attrs['placeholder'] = 'queer, contributor'
        self.fields['public_message'].widget.attrs.update({
            'placeholder': 'Alice identifies as queer and is a core contributor to codeofconduct.',
            'rows': 2
        })
        self.fields['private_message'].widget.attrs.update({
            'placeholder': 'You can reach them at me@somecontributorhomepage.alice',
            'rows': 2
        })

        self.helper = pure_helper()
        self.helper.layout = Layout(
            Fieldset('Creating a submission for {}'.format(project),
                     *self.Meta.fields),
            Submit('submit', 'Create', css_class='pure-button pure-button-primary')
        )

projects/views.py
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from django.core.urlresolvers import reverse, reverse_lazy
from django.views.generic import View, ListView, DetailView, DeleteView, CreateView, FormView, UpdateView
from django.db.models import Q
from django.contrib import messages
from braces.views import UserPassesTestMixin
from common.access_mixins import VerifiedEmailRequiredMixin
from .models import Project, Report, Submission, Vouch
from . import models
from . import forms

class ProjectIndex(ListView):
    context_object_name = 'projects'

    def get_queryset(self):
        # Show all projects if a moderator is logged in. Otherwise only show
        # verified or owned projects.
        u = self.request.user
        if u.is_authenticated() and u.is_moderator:
            return Project.objects.all().order_by('verified_date')

        return Project.objects.filter(
            Q(verified_date__isnull=False) |
            Q(user=u.pk)
        ).order_by('verified_date')

class ProjectIndexByTag(ProjectIndex):
    def get_queryset(self):
        qs = super(ProjectIndexByTag, self).get_queryset()
        return qs.filter(tags__slug=self.kwargs['tag'])

class ProjectDetail(DetailView):
    model = Project
    context_object_name = 'project'

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)

        if self.request.user.is_authenticated():
            context['submissions'] = self.object.get_submissions_for_user(self.request.user)
            context['reports']     = self.object.get_reports_for_user(self.request.user)
            context['has_vouched'] = Vouch.has_vouched(self.object, self.request.user)

        if self.object.user == self.request.user:
            context['can_edit'] = True

        return context

class ProjectOwnerPermissionsMixin(UserPassesTestMixin):
    permission_fail_message = 'You must be the project owner to perform the requested action.'

    def test_func(self, user):
        return Project.objects.filter(user=user,
                                      pk=self.request.resolver_match.kwargs['pk']).exists()

    def no_permissions_fail(self, request):
        messages.error(request, self.permission_fail_message)
        return redirect(reverse('projects:detail', args=(self.request.resolver_match.kwargs['pk'],)))


class ProjectUpdate(ProjectOwnerPermissionsMixin,
                    VerifiedEmailRequiredMixin,
                    UpdateView):
    model = Project
    form_class = forms.UpdateProjectForm
    template_name = 'projects/project_form.html'

class ProjectDelete(ProjectOwnerPermissionsMixin,
                    VerifiedEmailRequiredMixin,
                    DeleteView):
    model = Project
    template_name = 'projects/project_confirm_delete.html'
    success_url = reverse_lazy('projects:index')

class CreateProject(VerifiedEmailRequiredMixin, CreateView):
    form_class = forms.CreateProjectForm
    template_name = 'projects/project_form.html'

    # Automatically verify projects submitted by staff.
    def form_valid(self, form):
        form.instance.user = self.request.user
        if form.instance.user.is_staff:
            form.instance.verify(form.instance.user, False)
        return super(CreateProject, self).form_valid(form)

class ProjectVerify(UserPassesTestMixin, View):
    def get(self, request, *args, **kwargs):
        project = get_object_or_404(Project, pk=kwargs['pk'])
        project.verify(request.user)
        messages.success(request, '{} has been verified.'.format(project.name))
        return redirect(project.get_absolute_url())

    def test_func(self, user):
        return user.is_moderator

    def no_permissions_fail(self, request):
        messages.error(request, 'You must be a moderator to verify this project.')
        return redirect('/')

class ToggleVouch(VerifiedEmailRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        if request.GET.get('model', '') not in ['Project', 'Submission']:
            raise Http404()
        target = get_object_or_404(getattr(models, request.GET.get('model')), pk=request.GET.get('pk'))
        status = Vouch.toggle_vouch(target, request.user)
        messages.success(request, status)
        return redirect(target.get_absolute_url())

class SubmissionVerify(UserPassesTestMixin, View):
    def get(self, request, *args, **kwargs):
        submission = get_object_or_404(Submission, pk=kwargs['pk'])
        submission.verify(request.user)
        messages.success(request, 'Submission verified.')
        return redirect(submission.project.get_absolute_url())

    def test_func(self, user):
        return user.is_moderator

    def no_permissions_fail(self, request):
        messages.error(request, 'You must be a moderator to verify this submission.')
        return redirect('/')

class SubmissionCreate(VerifiedEmailRequiredMixin, CreateView):
    form_class = forms.CreateSubmissionForm
    template_name = 'projects/submission_form.html'

    def get_form_kwargs(self):
        kwargs = super(SubmissionCreate, self).get_form_kwargs()
        kwargs.update({
            'project': get_object_or_404(Project, pk=self.request.resolver_match.kwargs['pk'])
        })
        return kwargs

    def form_valid(self, form):
        project = get_object_or_404(Project, pk=self.request.resolver_match.kwargs['pk'])
        form.instance.project = project
        form.instance.user = self.request.user
        self.success_url = project.get_absolute_url()
        return super(SubmissionCreate, self).form_valid(form)

projects/templates/projects/_project_toolbar.html
{% load url_extras %}
{% load icons %}
<ul class="project-toolbar">
    {% if not project.verified_date and user.is_moderator %}
    <li><a class="pure-button pure-button-primary project-main-link" href="{% url "projects:verify" project.pk %}" title="Verify Project">{% icon "zmdi zmdi-check zmdi-fw" %} Verify</a></li>
    {% endif %}
    {% if project.homepage %}
    <li><a class="pure-button pure-button-primary project-main-link" href="{{ project.homepage }}" title="{{ project.homepage|netloc }}">{% icon "zmdi zmdi-home zmd-fw" %} {{ project.homepage|netloc|truncatewith:"20,Homepage" }}</a></li>
    {% endif %}
    {% if project.code_of_conduct %}
    <li><a class="pure-button pure-button-primary project-main-link" href="{{ project.code_of_conduct }}" title="Code of Conduct">{% icon "zmdi zmdi-face zmd-fw" %} Code of Conduct</a></li>
    {% endif %}

    <li><a class="pure-button pure-button-primary" href="{{ project.get_report_url }}" title="Report Project">{% icon "zmdi zmdi-flag zmd-fw" %} ({{ project.reports.count }}) Report Entry</a></li>
    <li>
        <a class="pure-button pure-button-primary" href="{{ project.get_vouch_url }}" title="Community Vouch">
            {% if has_vouched %}
            {% icon "zmdi zmdi-favorite zmd-fw" %} ({{ project.vouches.count }}) Remove Your Vouch
            {% else %}
            {% icon "zmdi zmdi-favorite-outline zmd-fw" %} ({{ project.vouches.count }}) Vouch For Community
            {% endif %}
        </a>
    </li>
    {% if can_edit %}
    <li><a class="pure-button pure-button-primary" href="{% url "projects:update" project.pk %}" title="Edit Project">{% icon "zmdi zmdi-edit zmd-fw" %} Edit</a></li>
    <li><a class="pure-button delete" href="{% url "projects:delete" project.pk %}" title="Delete Project (must confirm)">{% icon "zmdi zmdi-delete zmd-fw" %} Delete</a></li>
    {% endif %}
</ul>
<div style="clear: both;"></div>

projects/templates/projects/project_confirm_delete.html
{% extends "layout.html" %}

{% block content %}
<form method="POST" class="pure-form">
    {% csrf_token %}
    <p>Are you sure you want to delete the project &lsquo;{{ object }}&rsquo;?</p>
    <input type="submit" value="Delete" class="pure-button button-danger" />
</form>
{% endblock %}

projects/templates/projects/project_detail.html
{% extends "layout.html" %}

{% load url_extras %}
{% load icons %}
{% block content %}
{% include "projects/_project_toolbar.html" with has_vouched=has_vouched project=project can_edit=can_edit %}
<h2 class="project-name">
    <a class="local" href="{{ project.get_absolute_url }}" title="{{ project.name }}">{{ project.name }}</a>
</h2>

<ul id="project-tags">
{% for tag in project.tags.all %}
<li><a href="{% url "projects:list-by-tag" tag.slug %}" title="Projects tagged {{ tag.name }}">{% icon "zmdi zmdi-label-heart zmd-fw" %}{{ tag.name }}</a></li>
{% endfor %}
<div style="clear: both;"></div>
</ul>

{% if not project.verified_date %}
<div class="project-verification">
    <p><b>This project is awaiting verification.</b> A member of our staff has not yet approved this project for public listing. The information on this page may be wrong.</p>
</div>
{% endif %}

<a href="{% url "projects:create-submission" project.pk project.name|slugify %}" title="Add submission to this project">Add submission to this project</a>

<ul>
{% for submission in submissions %}
<li>
    Submission by {{ submission.user.name }} on {{ submission.created_date|date:"d M Y" }}
    <ul>
        {% if user.is_moderator and not submission.verified_date %}
        <li>This submission is awaiting verification: <a href="{% url "projects:verify-submission" submission.pk %}" title="Verify">Verify Submission</a></li>
        {% endif %}
        <li><a href="{{ submission.url }}" title="{{ submission.url|netloc }}">{{ submission.url|netloc }}</a></li>
        <li>{{ submission.is_contributor|yesno:"Project contributor," }}</li>
        <li>
            Tags:
            <ul>
                {% for tag in submission.tags.all %}
                <li>{{ tag.name }}</li>
                {% endfor %}
            </ul>
        </li>
        <li>Public message:<br />{{ submission.public_message }}</li>
        {% if user.is_moderator %}
        <li>You are seeing this private message because you are a moderator:<br />{{ submission.private_message }}</li>
        {% endif %}
    </ul>
</li>
{% endfor %}
</ul>

{% endblock %}
{% block altcontent %}
<div class="pure-g">
    <div class="pure-u-1 pure-u-md-1-2">
        {% if reports %}
            {% for report in reports.all %}
            <div class="project-report">
                <div class="report-title">
                    {% if user.is_moderator or report.user == user %}
                    (<a href="{% url "reports:update" report.pk %}" title="Modify Report">Modify</a>)
                    {% endif %}
                    {{ report.resolved|yesno:"Resolved,Unresolved" }} report from <span class="date">{{ report.created_date|date:"d M Y" }}</span> by <b>{% if report.user == user %}You{% else %}{{ report.user.name }}{% endif %}</b>
                </div>
                <div class="report-visibility">
                    {% if user.is_moderator %}
                    This report is visible to you because you are a moderator.
                    {% elif report.user == user %}
                    This report is visible to you because you filed the report.
                    {% elif report.visible_to_owner and user == project.user %}
                    This report is visible to you because {{ report.user.name }} made this report visible to the project owner.
                    {% endif %}
                </div>
                <div class="report-message">
                    <p>{{ report.message }}</p>
                </div>
            </div>
            {% endfor %}
        {% endif %}
    </div>
</div>
{% endblock %}

projects/templates/projects/project_form.html
{% extends "layout.html" %}

{% load crispy_forms_tags %}

{% block rowwrapper %}pure-u-1 pure-u-md-1-3{% endblock %}
{% block content %}
{% crispy form %}
{% endblock %}

projects/templates/projects/project_list.html
{% extends "layout.html" %}
{% load url_extras %}
{% load icons %}

{% block altcontent %}
<div class="pure-g">
    <div class="pure-u-1">
        {% if user.is_authenticated %}
        <a href="{% url "projects:create" %}" title="Submit a project for tracking." class="pure-button pure-button-primary">Submit a project for tracking</a>
        {% endif %}
    </div>
</div>
<div class="pure-g">
    <div class="pure-u-1">
        <ul id="project-list">
            {% for project in projects %}
            <li>
                <a href="{{ project.get_absolute_url }}" title="{{ project.name }}">{{ project.name }}</a>
                <ul>
                    {% if project.verified_date %}
                    <li>
                    Verified by {{ project.verified_by.name }} on {{ project.verified_date|date:"d M Y" }}
                    {% else %}
                    Awaiting verification...
                    </li>
                    {% endif %}
                    {% if project.homepage %}
                    <li><a href="{{ project.homepage }}" title="Homepage">{{ project.homepage|netloc }}</a></li>
                    {% endif %}
                    {% if project.code_of_conduct %}
                    <li><a href="{{ project.code_of_conduct }}" title="Code of Conduct">Code of Conduct</a></li>
                    {% endif %}
                    <li>
                        <ul>
                            {% for tag in project.tags.all %}
                            <li><a href="{% url "projects:list-by-tag" tag.slug %}" title="Projects tagged {{ tag.name }}">{% icon "zmdi zmdi-label-heart zmd-fw" %}{{ tag.name }}</a></li>
                            {% endfor %}
                        </ul>
                    </li>
                </ul>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

projects/templates/projects/submission_form.html
{% extends "layout.html" %}

{% load crispy_forms_tags %}

{% block rowwrapper %}pure-u-1 pure-u-md-1-3{% endblock %}
{% block content %}
{% crispy form %}
{% endblock %}